/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Love Byiringiro
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        projectBTN = new javax.swing.JButton();
        workerBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        backBTN1 = new javax.swing.JButton();
        backBTN2 = new javax.swing.JButton();
        backBTN3 = new javax.swing.JButton();
        backBTN4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/10.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 590, 940));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 600, 920));

        jPanel2.setBackground(new java.awt.Color(25, 21, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN DASHBOARD");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 20, -1, -1));

        projectBTN.setBackground(new java.awt.Color(255, 255, 255));
        projectBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        projectBTN.setForeground(new java.awt.Color(0, 51, 51));
        projectBTN.setText("Project Management ");
        projectBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectBTNActionPerformed(evt);
            }
        });
        jPanel2.add(projectBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 152, -1, -1));

        workerBTN.setBackground(new java.awt.Color(255, 255, 255));
        workerBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        workerBTN.setForeground(new java.awt.Color(0, 51, 51));
        workerBTN.setText("Workers Management");
        workerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerBTNActionPerformed(evt);
            }
        });
        jPanel2.add(workerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 240, 30));

        backBTN.setBackground(new java.awt.Color(255, 255, 255));
        backBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/replay.png"))); // NOI18N
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 600, 100, 60));

        backBTN1.setBackground(new java.awt.Color(255, 255, 255));
        backBTN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/replay.png"))); // NOI18N
        backBTN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        backBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN1ActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 600, 100, 60));

        backBTN2.setBackground(new java.awt.Color(255, 255, 255));
        backBTN2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBTN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/replay.png"))); // NOI18N
        backBTN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        backBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN2ActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 470, 100, 60));

        backBTN3.setBackground(new java.awt.Color(255, 255, 255));
        backBTN3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBTN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/replay.png"))); // NOI18N
        backBTN3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        backBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN3ActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 470, 100, 60));

        backBTN4.setBackground(new java.awt.Color(255, 255, 255));
        backBTN4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBTN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/replay.png"))); // NOI18N
        backBTN4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        backBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN4ActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 780, 100, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 780, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectBTNActionPerformed
        // Create an instance of the ProjectManagement form
            ProjectManagement pj = new ProjectManagement();

            // Make the Signup form visible
            pj.setVisible(true);

            // Close or hide the current form if necessary
            this.setVisible(false); // Hide the current form
            // OR
            this.dispose(); // Close the current form
    }//GEN-LAST:event_projectBTNActionPerformed

    private void workerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerBTNActionPerformed
        // Create an instance of the Signup form
            UserManagementDashoard user = new UserManagementDashoard();

            // Make the Signup form visible
            user.setVisible(true);

            // Close or hide the current form if necessary
            this.setVisible(false); // Hide the current form
            // OR
            this.dispose(); // Close the current form
    }//GEN-LAST:event_workerBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        AdminDashboard admin = new AdminDashboard();

        // Make the Signup form visible
        admin.setVisible(true);

        // Close or hide the current form if necessary
        this.setVisible(false); // Hide the current form
    }//GEN-LAST:event_backBTNActionPerformed

    private void backBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN1ActionPerformed
       
    }//GEN-LAST:event_backBTN1ActionPerformed

    private void backBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBTN2ActionPerformed

    private void backBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBTN3ActionPerformed

    private void backBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN4ActionPerformed
         Login lg = new Login();

        // Make the Signup form visible
        lg.setVisible(true);

        // Close or hide the current form if necessary
        this.setVisible(false); // Hide the current form
    }//GEN-LAST:event_backBTN4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton backBTN1;
    private javax.swing.JButton backBTN2;
    private javax.swing.JButton backBTN3;
    private javax.swing.JButton backBTN4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton projectBTN;
    private javax.swing.JButton workerBTN;
    // End of variables declaration//GEN-END:variables
}
