/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Love Byiringiro
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSTRUCTION MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 24, 703, -1));

        loading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loading.setForeground(new java.awt.Color(255, 255, 255));
        loading.setText("Loading...");
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 96, -1));

        progressBar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        progressBar.setForeground(new java.awt.Color(0, 204, 0));
        progressBar.setStringPainted(true);
        jPanel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 996, 29));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/4.jpg"))); // NOI18N
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1020, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       HomePage hp = new HomePage();
        Login lf = new Login();
        hp.setVisible(true);
        for(int i = 1; i<=100; ++i){
            try {
                Thread.sleep(80);
                hp.progressBar.setValue(i);
                
                if(i%2 == 0 ){
                    hp.loading.setText("Loading...");
                }else {
                    hp.loading.setText("Loading...");

                }
                if(i== 100) {
                    hp.setVisible(false);
                    lf.setVisible(true);
                    
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel loading;
    public static javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
