/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.UserDao;
import javax.swing.JOptionPane;
import model.User;
import util.ValidationUtils;

/**
 *
 * @author Love Byiringiro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userIDTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        signupBTN = new javax.swing.JButton();
        loginBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/8.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imageLabel))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        jPanel2.setBackground(new java.awt.Color(25, 21, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        userIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(userIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 166, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        passwordPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(passwordPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 166, -1));

        signupBTN.setBackground(new java.awt.Color(255, 255, 255));
        signupBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signupBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/signup.png"))); // NOI18N
        signupBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBTNActionPerformed(evt);
            }
        });
        jPanel2.add(signupBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 90, 40));

        loginBTN.setBackground(new java.awt.Color(255, 255, 255));
        loginBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/log-in.png"))); // NOI18N
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        jPanel2.add(loginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't have an account, please Signup!");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/login.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/padlock.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        exitBTN.setBackground(new java.awt.Color(25, 21, 74));
        exitBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/shutdown.png"))); // NOI18N
        exitBTN.setBorderPainted(false);
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        jPanel2.add(exitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 90, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 490, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBTNActionPerformed
              // Create an instance of the Signup form
            Signup signupForm = new Signup();

            // Make the Signup form visible
            signupForm.setVisible(true);

            // Close or hide the current form if necessary
            this.setVisible(false); // Hide the current form
            // OR
            this.dispose(); // Close the current form
    }//GEN-LAST:event_signupBTNActionPerformed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
         // Retrieve values from input fields
    String userID = userIDTextField.getText().trim();
    String password = new String(passwordPasswordField.getPassword());

    // Validate fields
    if (!ValidationUtils.validateLoginFields(userID, password)) {
        return;  // Exit the method if validation fails
    }

    // Perform login authentication
    User authenticatedUser = authenticateUser(userID, password);

    // Check if authentication was successful
    if (authenticatedUser != null) {
        // Redirect to the appropriate dashboard based on the user's role
        if (authenticatedUser.getRole().equals("Admin")) {
    AdminDashboard admin = new AdminDashboard();

    // Make the AdminDashboard form visible
    admin.setVisible(true);

    // Close or hide the current login form
    this.setVisible(false); // Hide the current form
    // OR
    this.dispose(); // Close the current form
} else if (authenticatedUser.getRole().equals("User")) {
    UserDashBoard userDashboard = new UserDashBoard();

    // Assuming updateUserDetails sets user details in the dashboard
    userDashboard.updateUserDetails(
        authenticatedUser.getUserID(),
        authenticatedUser.getFullNames(),
        authenticatedUser.getPhoneNumber(),
        authenticatedUser.getPosition()
    );

    // Make the UserDashboard form visible
    userDashboard.setVisible(true);

    // Close or hide the current login form
    this.setVisible(false); // Hide the current form
    // OR
    this.dispose(); // Close the current form
}

    } else {
        // Display error message for unsuccessful login
        JOptionPane.showMessageDialog(this, "Invalid credentials. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_loginBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed
    private User authenticateUser(String userID, String password) {
        UserDao userDao = new UserDao("jdbc:mysql://localhost:3306/construction_management_system_db", "root", "");

        // Call the getUserByCredentials method from UserDao
        return userDao.getUserByCredentials(userID, password);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBTN;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JButton signupBTN;
    private javax.swing.JTextField userIDTextField;
    // End of variables declaration//GEN-END:variables
}
