package view;

import DAO.UserDao;
import javax.swing.JOptionPane;
import model.User;
import util.UserIDGenerator;
import util.ValidationUtils;
import static util.ValidationUtils.isEligibleForAdmin;

/**
 *
 * @author Love Byiringiro
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fullNamesTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        positionComboBox = new javax.swing.JComboBox<>();
        registerBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        confirmPasswordTextField = new javax.swing.JPasswordField();
        passwordTextField = new javax.swing.JPasswordField();
        nationalIDTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        backBTN = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FULLNAMES");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NATIONAL ID");

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/6.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 630));

        jPanel2.setBackground(new java.awt.Color(21, 25, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGNUP");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 38, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FULLNAMES:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 211, -1, -1));

        fullNamesTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(fullNamesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 208, 239, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NATIONAL ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 164, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("POSITION:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 326, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE NUMBER:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 269, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ROLE:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        positionComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        positionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laborer", "Carpenter", "Electrician", "Mason", "Welder", "Plumber", "Painter", "Supervisor", "Foreman", "Executives or Owners ", "Human Resources (HR)" }));
        positionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(positionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 325, 239, -1));

        registerBTN.setBackground(new java.awt.Color(255, 255, 255));
        registerBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerBTN.setForeground(new java.awt.Color(0, 51, 51));
        registerBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/register.png"))); // NOI18N
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });
        jPanel2.add(registerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 80, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PASSWORD:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 386, -1, -1));

        roleComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel2.add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 233, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONFIRM PASSWORD:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));
        jPanel2.add(confirmPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 230, 30));
        jPanel2.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 230, 30));

        nationalIDTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(nationalIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 240, -1));

        phoneNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 240, -1));

        backBTN.setBackground(new java.awt.Color(255, 255, 255));
        backBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBTN.setForeground(new java.awt.Color(0, 51, 51));
        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/previous.png"))); // NOI18N
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 70, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 590, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void positionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionComboBoxActionPerformed
        System.out.println("Selected Position: " + positionComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_positionComboBoxActionPerformed

    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTNActionPerformed
         // Retrieve values from input fields
        String nationalID = nationalIDTextField.getText().trim();
        String fullNames = fullNamesTextField.getText().trim();
        String phoneNumber = phoneNumberTextField.getText().trim();
        String password = new String(passwordTextField.getPassword());
        String confirmPassword = new String(confirmPasswordTextField.getPassword());

        // Validate Role and Position (ComboBoxes)
        String selectedRole = roleComboBox.getSelectedItem().toString();
        String selectedPosition = positionComboBox.getSelectedItem().toString();

        // Print values for debugging
        System.out.println("Selected Position: " + selectedPosition);
        System.out.println("Selected Role: " + selectedRole);

        if ("Select Role".equals(selectedRole) || "Select Position".equals(selectedPosition)) {
            JOptionPane.showMessageDialog(null, "Please select a valid Role and Position.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if non-eligible roles are trying to select Admin
        System.out.println("Before eligibility check - Selected Position: " + selectedPosition);
        System.out.println("Before eligibility check - Selected Role: " + selectedRole);
        if (selectedRole.equals("User")) {
        // No need to check eligibility for Admin
      } else {
        if (!isEligibleForAdmin(selectedPosition, selectedRole)) {
          JOptionPane.showMessageDialog(null, "You are not eligible to select the Admin role.", "Error", JOptionPane.ERROR_MESSAGE);
          return;
        }
      }


        // Validate fields
        if (!ValidationUtils.validateFields(nationalID, fullNames, phoneNumber, password, confirmPassword, roleComboBox, positionComboBox)) {
            return;  // Exit the method if validation fails
        }

        // Generate UserID
        String userID = UserIDGenerator.generateUserID(fullNames);

        // Determine the role
        String role = ValidationUtils.determineRole(selectedPosition, selectedRole);

        // Print values for debugging
        System.out.println("After eligibility check - Selected Position: " + selectedPosition);
        System.out.println("After eligibility check - Selected Role: " + selectedRole);
        System.out.println("Determined Role: " + role);


        


        // Create a User object
        User user = new User();
        user.setUserID(userID);
        user.setNationalID(nationalID);
        user.setFullNames(fullNames);
        user.setPhoneNumber(phoneNumber);
        user.setPassword(password);
        user.setConfirmPassword(confirmPassword);
        user.setRole(role);
        
        // Set the position
        user.setPosition(positionComboBox.getSelectedItem().toString());


        // Insert the user into the database
        UserDao userDao = new UserDao("jdbc:mysql://localhost:3306/construction_management_system_db", "root", "");
        boolean registrationSuccess = userDao.addUser(user);

        if (registrationSuccess) {
            JOptionPane.showMessageDialog(this, "Registration Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearInputFields();
        } else {
            JOptionPane.showMessageDialog(this, "Registration Failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
}

// Helper method to clear input fields
private void clearInputFields() {
    nationalIDTextField.setText("");
    fullNamesTextField.setText("");
    phoneNumberTextField.setText("");
    passwordTextField.setText("");
    confirmPasswordTextField.setText("");
    roleComboBox.setSelectedIndex(0);
    positionComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_registerBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // Create an instance of the ProjectManagement form
            Login lg = new Login();

            // Make the Signup form visible
            lg.setVisible(true);

            // Close or hide the current form if necessary
            this.setVisible(false); // Hide the current form
            // OR
            this.dispose(); // Close the current form
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JTextField fullNamesTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nationalIDTextField;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JComboBox<String> positionComboBox;
    private javax.swing.JButton registerBTN;
    private javax.swing.JComboBox<String> roleComboBox;
    // End of variables declaration//GEN-END:variables
}
