/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ProjectDao;
import DAO.RequestDao;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javafx.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import model.Project;
import model.Request;

/**
 *
 * @author Love Byiringiro
 */
public class UserDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashBoard
     */
    public UserDashBoard() {
        initComponents();
        setupProjectsJTable();
    }
    private String loggedInUserID;
    private JDialog descriptionDialog;

private void setupProjectsJTable() {
    // Define the column names
    String[] columnNames = {"Project ID", "Name", "Description", "Location", "Start Date", "End Date"};

    // Create a DefaultTableModel with the specified columns
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    projectjTable.setModel(model);
    

    // Retrieve data from the database and add it to the table
    ProjectDao projectDao = new ProjectDao("jdbc:mysql://localhost:3306/construction_management_system_db", "root", "");
    List<Project> projectList = projectDao.getAllProjects();

    for (Project project : projectList) {
    Object[] rowData = {project.getProjectID(), project.getName(), project.getDescription(), project.getLocation(), project.getStartDate(), project.getEndDate()};
    model.addRow(rowData);

    // Convert the integer Project ID to String before adding it to the combo box
    jComboProject.addItem(String.valueOf(project.getProjectID()));
}

    // Set up a mouse listener to detect clicks on the "Description" column
        projectjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int column = projectjTable.columnAtPoint(evt.getPoint());
                int row = projectjTable.rowAtPoint(evt.getPoint());

                // Assuming "Description" is the third column (index 2)
                if (column == 2 && row >= 0) {
                    // Display a pop-up window with the full content of the cell
                    showDescriptionDialog(projectjTable.getValueAt(row, column).toString());
                }
            }
        });
}
private void showDescriptionDialog(String description) {
        if (descriptionDialog == null) {
            descriptionDialog = new JDialog(this, "Description Details", true);
            descriptionDialog.setSize(500, 300);
            descriptionDialog.setLocationRelativeTo(this);

            JTextArea descriptionTextArea = new JTextArea();
            descriptionTextArea.setEditable(false);
            descriptionTextArea.setLineWrap(true);
            descriptionTextArea.setWrapStyleWord(true);
            JScrollPane scrollPane = new JScrollPane(descriptionTextArea);
            descriptionDialog.add(scrollPane);

            JButton closeButton = new JButton("Close");
            closeButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    descriptionDialog.dispose();
                }
            });

            descriptionDialog.add(BorderLayout.SOUTH, closeButton);
        }

        JTextArea descriptionTextArea = (JTextArea) ((JScrollPane) descriptionDialog.getContentPane().getComponent(0)).getViewport().getView();
        descriptionTextArea.setText(description);

        descriptionDialog.setVisible(true);
    }
public void updateUserDetails(String userID, String fullNames, String phoneNumber, String position) {
        loggedInUserID = userID; // Set the class variable to the logged-in user's ID
        jLabel14.setText("USER ID: " + userID);
        jLabel3.setText("FULLNAMES: " + fullNames);
        jLabel8.setText("PHONE NUMBER: " + phoneNumber);
        jLabel7.setText("POSITION: " + position);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        imageLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectjTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboProject = new javax.swing.JComboBox<>();
        requestBTN = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        checkBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        jPanel2.setBackground(new java.awt.Color(30, 27, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER DASHBOARD");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 320, 50));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/workers.png"))); // NOI18N
        imageLabel.setText("image");
        jPanel2.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 70, 70));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("STATUS:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FULLNAMES:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 350, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE NUMBER:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 370, -1));

        imageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/information.png"))); // NOI18N
        jPanel2.add(imageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 160));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("POSITION:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 290, -1));

        projectjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(projectjTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 760, 128));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Project Data Table");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USER ID:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jComboProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboProjectActionPerformed(evt);
            }
        });
        jPanel2.add(jComboProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 160, 20));

        requestBTN.setBackground(new java.awt.Color(255, 255, 255));
        requestBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        requestBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/apply.png"))); // NOI18N
        requestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBTNActionPerformed(evt);
            }
        });
        jPanel2.add(requestBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 90, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PROJECT ID:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        statusTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 170, -1));

        checkBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/clipboard.png"))); // NOI18N
        checkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTNActionPerformed(evt);
            }
        });
        jPanel2.add(checkBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 90, -1));

        backBTN.setBackground(new java.awt.Color(255, 255, 255));
        backBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/replay.png"))); // NOI18N
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel2.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 560, 100, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        Login lg = new Login();

        // Make the Signup form visible
        lg.setVisible(true);

        // Close or hide the current form if necessary
        this.setVisible(false); // Hide the current form
    }//GEN-LAST:event_backBTNActionPerformed

    private void jComboProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProjectActionPerformed

    private void requestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBTNActionPerformed
         ProjectDao projectDao = new ProjectDao("jdbc:mysql://localhost:3306/construction_management_system_db", "root", "");
        RequestDao requestDao = new RequestDao();

        List<Project> projects = projectDao.getAllProjects();
        jComboProject.removeAllItems();
        Map<String, Project> projectMap = new HashMap<>();

        for (Project project : projects) {
            jComboProject.addItem(project.getName());
            projectMap.put(project.getName(), project);
        }

        String selectedProjectName = (String) jComboProject.getSelectedItem();
        Project selectedProject = projectMap.get(selectedProjectName);

        if (selectedProject != null) {
            try {
                String status = "Pending";
                Request request = new Request();
                request.setProjectID(selectedProject.getProjectID());
                request.setUserID(loggedInUserID); // Use the logged-in user's ID
                request.setStatus(status);

                String result = requestDao.requestInput(request);

                if (result.equals("Request Registered")) {
                    JOptionPane.showMessageDialog(this, "Request Registered Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Register Request", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error Occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a project", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_requestBTNActionPerformed

    private void checkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTNActionPerformed
        String loggedInUserID = this.loggedInUserID; // Use the stored logged-in user's ID
    
    if (loggedInUserID != null) {
        RequestDao requestDao = new RequestDao(); // Create an instance of RequestDao
        
        // Fetch status of the logged-in user
        String userStatus = requestDao.getUserStatus(loggedInUserID);
        
        // Display the user's status in the statusTxt field
        statusTxt.setText(userStatus);
    } else {
        // Handle case where logged-in user ID is not found
        JOptionPane.showMessageDialog(this, "User ID not found", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_checkBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton checkBTN;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imageLabel1;
    private javax.swing.JComboBox<String> jComboProject;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable projectjTable;
    private javax.swing.JButton requestBTN;
    private javax.swing.JTextField statusTxt;
    // End of variables declaration//GEN-END:variables
}
